version: '3'

# volumes:
#   db-data:

services:
  db:
    image: postgres:14
    container_name: db
    volumes:
      - ./docker/db/data:/var/lib/postgresql/study_chat_development/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: study_chat_development
